### ISSUE TITLE
UX enhancement : IOS version can not close the keyboard after opening it 

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/myceliumflut#53]
After clicking on the peer field can not close the keyboard while using the app
https://github.com/user-attachments/assets/d1320f9c-59da-4398-9f8f-4c38f3e95014

![telegram-cloud-photo-size-4-5900218654845420370-y](https://github.com/user-attachments/assets/6c130485-f233-4bb7-ae77-3e82f68adc46)

**Comment by iwanbk** [comment]
thanks @khaledyoussef24 , i can reproduce the issue

**Comment by iwanbk** [comment]
Fixed on #56

**Comment by iwanbk** [comment]
reopen again because it needs verification

**Comment by khaledyoussef24** [comment]
fixed and verified 

https://github.com/user-attachments/assets/f9590374-4ec8-4a08-bc2a-e618402f9514



[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/244166?expand_section=447543#case_4340972)
