### ISSUE TITLE
can not stop mycelium

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/myceliumflut#54]
after starting mycelium i can not stop it again
![telegram-cloud-photo-size-4-5900218654845420371-y](https://github.com/user-attachments/assets/9cf87fd7-a90e-45a8-9c03-c30112c20d7d)
![telegram-cloud-photo-size-4-5900218654845420370-y](https://github.com/user-attachments/assets/f30b305b-b0f1-4340-8f6c-f76a0871b186)

https://github.com/user-attachments/assets/6cd57dac-3541-46fc-acea-677ac00d8a50

**Comment by khaledyoussef24** [comment]
the same issue is reproduced on mac os
<img width="1680" alt="Screenshot 2024-08-14 at 12 07 19 PM" src="https://github.com/user-attachments/assets/40be7522-7708-47d0-ab9f-713771567afa">
<img width="1680" alt="Screenshot 2024-08-14 at 12 07 21 PM" src="https://github.com/user-attachments/assets/04de10bc-bced-4446-bc0e-0b9e58ec9c13">

**Comment by khaledyoussef24** [comment]
after investigating the issue is only produced the first time you use the app after installing (after setting up the vpn and giving permissions to it)

**Comment by iwanbk** [comment]
> the same issue is reproduced on mac os

Hi @khaledyoussef24 
The app is not tested on mac OS. It only supposed to work on iphone.

Maybe Mac OS can be included in the next version, cc @xmonader @maximevanhees

**Comment by iwanbk** [comment]
> after investigating the issue is only produced the first time you use the app after installing (after setting up the vpn and giving permissions to it)

I can reproduce the issue.
It is because very first run is indeed problematic, it already fixed at #32.
Will check why it happens again.

On the other hand, the UI must handle this gracefully.

**Comment by iwanbk** [comment]
@khaledyoussef24 i fixed it at #57 

Do you need me to make it available on TestFlight or you can build it directly from the repo?

**Comment by khaledyoussef24** [comment]
I was testing from the test flight version i may try to use android or emilatour

**Comment by iwanbk** [comment]
> I was testing from the test flight version

OK, i'll upload to testflight tomorrow because Sunday is not working day here

> i may try to use android or emilatour

The fix is specific for iOS.
Mycelium also doesn't work on iphone emulator.
So, only testflight or running using xcode

**Comment by iwanbk** [comment]
> OK, i'll upload to testflight tomorrow because Sunday is not working day here

uploaded to testFlight, pls check @khaledyoussef24

**Comment by iwanbk** [comment]
> OK, i'll upload to testflight tomorrow because Sunday is not working day here

uploaded to TestFlight, pls check @khaledyoussef24

**Comment by khaledyoussef24** [comment]
the issue is no longer reproducible. I tried on different platforms but could not produce
