### ISSUE TITLE
Restart mycelium enhancement

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/myceliumflut#55]
After clicking on 'Restart Mycelium,' we could change the message to 'Mycelium is restarting' before the other message "mycelium restarted " to inform the user that the process has begun, confirming that the button was successfully activated.
<img width="1680" alt="Screenshot 2024-08-14 at 12 01 21 PM" src="https://github.com/user-attachments/assets/e8656642-aad5-45ea-8ccb-070d39265ab8">
<img width="1680" alt="Screenshot 2024-08-14 at 12 01 37 PM" src="https://github.com/user-attachments/assets/d5e5c5bb-171b-45b0-97c0-04cf731c2d9d">

**Comment by iwanbk** [comment]
Hi @khaledyoussef24 
what happens right now when we do restart:
- stopping the mycelium -> then `mycelium stopped` will be displayed
- start the mycelium -> then `mycelium started` will be displayed.

It happens very fast on my android & iphone that only `mycelium started` that i can see completely.

Sure i could add `mycelium is restarting` before stopping mycelium, but it will be unnoticeable IMO.

Wdyt?

**Comment by iwanbk** [comment]
cc @ehab-hassan your input would be appreciated.

**Comment by ehab-hassan** [comment]
@khaledyoussef24 when I tried it, it happened fast the user will not see "Mycelium is restarting"

**Comment by khaledyoussef24** [comment]
verified the message now appears even if in a just quick way
<img width="1680" alt="Screenshot 2024-09-26 at 4 41 32 PM" src="https://github.com/user-attachments/assets/9b032068-437e-400a-86f6-2f49932b9e5b">


[testcase](https://app.testlodge.com/a/26076/projects/40893/suites/244166?expand_section=447543#case_4340967)
