### ISSUE TITLE
Testing Myceliumflut Desktop

### ISSUE THREAD

**Issue by khaledyoussef24** [threefoldtech/myceliumflut#66]
Testing the Myceliumflut Desktop application to identify any performance issues or bugs.
Desktop versions :

- [x] Windows
- [x] Macos

**Comment by nourakhy** [comment]
download
https://bit.ly/4evXrQ6

you may need to install the c compiler

**Comment by khaledyoussef24** [comment]
I started with macos version and it is working fine
![Screenshot 2024-09-19 at 1 16 17 PM (2)](https://github.com/user-attachments/assets/e3e0a514-c0a5-4d35-9311-c450928a645e)
some times (occurred only once in 3 days) could not connect and used restart button then worked fine.

**Comment by khaledyoussef24** [comment]
was testing on windows faced multiple issue 
the first issue faced me while running the app was it was not starting

https://github.com/user-attachments/assets/61da7e4d-237e-4bf9-a313-298588619674

 we should run the app as an administrator (we should mention this in docs)
worked fine but still trying to connect to machines (checking ssh confgs for windows)

https://github.com/user-attachments/assets/c3292773-4969-437d-bf16-4e9dc3b07dd8

**Comment by khaledyoussef24** [comment]
can we make a detailed docs going through Windows because I could not make it work 
I am stuck for so long i even tried myceliumflut and could not connect 
![image](https://github.com/user-attachments/assets/5a978b3d-6e02-49f4-9175-b04427f7f514)
![image](https://github.com/user-attachments/assets/483ae4de-54f6-44f9-b97c-70beab488036)

**Comment by iwanbk** [comment]
Hi @khaledyoussef24 

> we should run the app as an administrator (we should mention this in docs)

You can do this for now, my Windows user is administrator so i didn't realize this.

> worked fine but still trying to connect to machines (checking ssh confgs for windows)

The easiest way is using `ping6`:
1. Start myceliumflut on your Windows, as administrator
![image](https://github.com/user-attachments/assets/f2a6eb6b-08ee-40c4-b2e1-0004c64ca5e7)

there are two values there:
- `IP Address` is the myceliumflut IPv6 address
- `peers` is the public node that we use, we can use more than one public nodes

2. start mycelium on other machine, maybe on your linux, **with same `peers`** as your windows myceliumflut
3. get the IPv6 of your myceliumflut on windows, (you can copy paste it)
4. ping that IP using `ping6`
```console
#ping6 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b
PING6(56=40+8+8 bytes) 409:78d9:eed3:30ff:70fb:d059:774d:8dae --> 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b
16 bytes from 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b, icmp_seq=0 hlim=125 time=307.620 ms
16 bytes from 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b, icmp_seq=1 hlim=125 time=309.576 ms
16 bytes from 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b, icmp_seq=2 hlim=125 time=361.479 ms
16 bytes from 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b, icmp_seq=3 hlim=125 time=306.593 ms
16 bytes from 4ed:43f8:bd08:f94f:ebb9:aace:5f58:2f1b, icmp_seq=4 hlim=125 time=309.126 ms
```

For Windows, i can't give guide to test by connecting to sshd on Windows because i failed to configure SSHD server on Windows.

But `ping6` is more than enough for connectivity testing.

**Comment by khaledyoussef24** [comment]
tried everything mentioned i even pinged with `ping -6 ` to make sure that the ping process is functional
but still could not connect to the machine (even though the ping was successful)
<img width="536" alt="Screenshot 2024-10-07 at 3 43 01 PM" src="https://github.com/user-attachments/assets/b89f129e-8a63-40eb-8f01-6fc86934c2c0">
<img width="872" alt="Screenshot 2024-10-07 at 4 02 49 PM" src="https://github.com/user-attachments/assets/8e517b6a-24cf-49e8-b16f-139f1d985af2">
<img width="734" alt="Screenshot 2024-10-07 at 4 03 22 PM" src="https://github.com/user-attachments/assets/1126049d-773e-49b8-85a7-b4e1d0cc34af">
<img width="1680" alt="Screenshot 2024-10-07 at 4 05 06 PM" src="https://github.com/user-attachments/assets/d1edb06b-f521-41ae-9c4a-f563c70f24fb">

Even tried the binary from mycelium repo faced this `←[2m2024-10-07T14:06:16.821906Z←[0m ←[33m WARN←[0m ←[2mmycelium::data←[0m←[2m:←[0m Data inject loop from host to router ended`

**Comment by iwanbk** [comment]
> tried everything mentioned i even pinged with ping -6  to make sure that the ping process is functional
but still could not connect to the machine (even though the ping was successful)

actually if ping works, then very most likely mycelium works.
As for connecting to the windows machine, it is different things. And i don't test it either.
Lot of things can make it failed. And unfortunately i can't help you, maybe Peter knows?

Maybe you can connect to the windows machine using the ipv4?

**Comment by iwanbk** [comment]
Hi @khaledyoussef24 , i know nothing about mobaxtreme.
But i curious about these:
1. how is it's config? does it listen to all interface or only to the IPv4
2. if to all interfaces, maybe you can try to restart the ssh server after starting mycelium

**Comment by khaledyoussef24** [comment]
@iwanbk Yes, it listens to all interfaces (it is just like a normal terminal for Windows) I even used it to ping mycelium ip and it worked just fine.
yes, I tried to restart mycelium many times.

**Comment by iwanbk** [comment]
just want to clarify the setups, please confirm:
1. install mobaxtreme on windows machine
2. run myceliumflut on WIndows
3. run mycelium on Linux
4. do ssh from windows to linux

I thought you did ssh from linux to windows, but after i checked `mobaxtreme`, it only has SSH client.

That scenario works for me, but i use `ssh` client from the windows powershell

**Comment by iwanbk** [comment]
to localize the issue, i think you can `do ssh from one linux to other linux, using mycelium IP`.

Btw, you can always ping me on telegram.

**Comment by khaledyoussef24** [comment]
> just want to clarify the setups, please confirm:
> 
> 1. install mobaxtreme on windows machine
> 2. run myceliumflut on WIndows
> 3. run mycelium on Linux
> 4. do ssh from windows to linux
> 
> I thought you did ssh from linux to windows, but after i checked `mobaxtreme`, it only has SSH client.
> 
> That scenario works for me, but i use `ssh` client from the windows powershell

Yes, this is exactly what I had done.

**Comment by khaledyoussef24** [comment]
### tested myceliumflut for windows


**steps made :**

1. downloaded myceliumflut on windows 
2. started the app myceliumflut and put and peers 
3. started mycelium connection
4. tried to ping the Linux machine (server with Mycelium installed on it ), and it pinged fine 
5. connected fine and faced no problem

![telegram-cloud-photo-size-4-5778481758210212434-y](https://github.com/user-attachments/assets/ca303b55-0696-44ce-8432-6c470b289c07)
![telegram-cloud-photo-size-4-5778481758210212437-y](https://github.com/user-attachments/assets/e0c8f846-295c-497d-8a8e-0a0273dbdaf9)
![telegram-cloud-photo-size-4-5778481758210212441-y](https://github.com/user-attachments/assets/dd1d848f-7efe-4e0e-b65d-93d51b54109a)

cons : could not connect to machines deployed throughout the grid

**Comment by khaledyoussef24** [comment]
myceliumflut latest version made by Iwan worked fine and while running the app ,I could connect to machines on the grid using mycelium ip
![telegram-cloud-photo-size-4-5819062692281960362-y](https://github.com/user-attachments/assets/832a5270-ead5-40a3-a02f-de1f5417d58c)

**Comment by iwanbk** [comment]
close it because already fixed and tested
