### ISSUE TITLE
icon & feature graphic for google playstore

### ISSUE THREAD

**Issue by iwanbk** [threefoldtech/myceliumflut#96]
Need these files for the google playstore listing

**app icon**
Your app icon must be a PNG or JPEG, up to 1 MB, 512 px by 512 px, and meet our [design specifications](https://developer.android.com/google-play/resources/icon-design-specifications) and [metadata policy](https://support.google.com/googleplay/android-developer/answer/9898842)

**feature graphic**
Your feature graphic must be a PNG or JPEG, up to 15 MB, and 1,024 px by 500 px

For feature graphic, i think we could use the app screenshot
![telegram-cloud-photo-size-5-6109693783353441840-y](https://github.com/user-attachments/assets/85b75668-565a-43a3-9921-ff6a212de225)

**Comment by ehab-hassan** [comment]
![mycelium_icon](https://github.com/user-attachments/assets/a8955c70-ec4c-4f8a-aab2-89d7c1a061f6)
check this for the App Store icon

for the feature graphic can u send me a screenshot at telegram or send me the last APK version and I ll do it

**Comment by iwanbk** [comment]
> check this for the App Store icon

It works, thanks

> for the feature graphic can u send me a screenshot at telegram or send me the last APK version and I ll do it

send the screenshots to Telegram.
latest .apk also available on the github release assets https://github.com/threefoldtech/myceliumflut/releases/tag/v0.8.0

**Comment by ehab-hassan** [comment]
Work in Progress (WIP):
I sent another logo for the icon to make it a bit smaller and sent a feature graphic resized to 1024*500 on telegram

**Comment by iwanbk** [comment]
all images has been accepted by google playstore
